FROM rustlang/rust:nightly AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin fastfs-sub-indexer

FROM debian:trixie-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/fastfs-sub-indexer /usr/local/bin/
CMD ["fastfs-sub-indexer"]
